web/eoxer/forms.py
''' Flask forms to be used on html pages with a set of validators '''
# IMPORT
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, validators

# CONST
PID_REGEXP = r'^[A-z\d\s\/\-\.+=]+$'
PID_MSG_LEN = 'Ошибка: не менее 4 символов, не более 200'
PID_MSG_REQ = 'Ошибка: укажите не менее одного артикула'
PID_MSG_REGEXP = 'Ошибка: используйте только латиницу, цифры, пробелы или символы /-.+='

CCFILE_MSG_EXT = 'Ошибка: выберите файл XLS'


# CLASS
class PidForm(FlaskForm):
    ''' Form to be filled by partnumbers '''
    pids = StringField('pids', [
        validators.Length(min=4, max=200, message=PID_MSG_LEN),
        validators.DataRequired(message=PID_MSG_REQ),
        validators.Regexp(PID_REGEXP, message=PID_MSG_REGEXP)
    ])


class CcFileForm(FlaskForm):
    ''' Form to select and upload a new version of Cisco Category XLS File'''
    # ccfile = FileField('ccfile')
    ccfile = FileField(
        'ccfile',
        [FileRequired(),
         FileAllowed(['xls', 'xlsx'], message=CCFILE_MSG_EXT)])

web/eoxer/__init__.py
""" Eoxer flask app """

web/eoxer/app.py
# IMPORT
from os import path

from flask import Flask
from jinja2_markdown import MarkdownExtension
from sentry_sdk import init as sentry_init
from flask_excel import init_excel

from eoxer.config import ProdConfig
from eoxer.views import all_blueprints
from eoxer.errors import eh
from eoxer.vars import get_sentry_dsn

# CONST
APP_DIR = path.abspath(path.dirname(__file__))
TEMPLATE_DIR = path.join(APP_DIR, 'templates')
STATIC_DIR = path.join(APP_DIR, 'static')


# FUNCTION
def create_app(config_object=ProdConfig):
    """ An application factory """
    # creating an instance of app
    app = Flask(
        __name__,
        instance_relative_config=True,
        template_folder=TEMPLATE_DIR,
        static_folder=STATIC_DIR)
    
    # excel module
    init_excel(app)

    # instance of Sentry
    sentry_dsn = get_sentry_dsn()
    if sentry_dsn:
        sentry_init(sentry_dsn)

    # does not strictly require slashes
    app.url_map.strict_slashes = False

    # load up a config
    app.config.from_object(config_object)

    # registering blueprints
    for bp in all_blueprints:
        app.register_blueprint(bp)

    # registering errorhandlers
    app.register_blueprint(eh)

    # adding extentions
    # support of markdown to jinja
    app.jinja_env.add_extension(MarkdownExtension)

    return app

web/eoxer/views.py
# IMPORT
from os import path, remove
from time import strftime, localtime
from collections import OrderedDict
from json import loads, dumps

from flask import render_template, request, current_app
from flask import Response, Blueprint
from flask_excel import make_response_from_records
from werkzeug.utils import secure_filename

from eoxer.search_eox import search_eox, parse_api_response
from eoxer.search_cc import search_cc_version, search_cc_substring
from eoxer.update_cc import update_cc
from eoxer.forms import PidForm, CcFileForm

# BLUEPRINT
bp_index = Blueprint('_index', "/")
bp_search_eox = Blueprint('_search_eox', __name__)
bp_export_eox = Blueprint('_export_eox', __name__)
bp_search_cc = Blueprint('_search_cc', __name__)
bp_update_cc = Blueprint('_update_cc', __name__)
bp_help = Blueprint('_help', __name__)

all_blueprints = (bp_index, bp_search_eox, bp_export_eox, bp_search_cc,
                  bp_update_cc, bp_help)


# ROUTE
# Start page
@bp_index.route('/', methods=['GET'])
def _index():
    form = PidForm()

    # just a normal page
    return render_template('index.html', form=form)


# Result page
@bp_search_eox.route('/search_eox', methods=['GET'])
def _search_eox():
    # collecting passed args and passing them to a form
    args = request.args
    form = PidForm(args)

    # if validation went successfully
    if form.validate():

        # extracting a list of pids
        raw_pids = request.args.get('pids')

        # do the job
        raw_eox, raw_obsolete, raw_active, raw_wrong, api_responses = search_eox(
            raw_pids)

        # prepare the lists of active and wrong pids
        active_pids = ", ".join(raw_active).strip(", ")
        wrong_pids = ", ".join(raw_wrong).strip(", ")

        # return a result
        return render_template(
            'search_eox.html',
            eox_pids=raw_eox,
            obsolete_pids=raw_obsolete,
            active_pids=active_pids,
            wrong_pids=wrong_pids,
            api_responses=api_responses)

    return render_template("index.html", form=form), 307


# Export EOX result to an Excel file
@bp_export_eox.route('/export_eox', methods=['POST'])
def _export_eox():
    # extracting json with EoXed PIDs from vars
    api_responses = request.values.get("api_responses")

    # extracting Active pids from vars
    active_pids = request.values.get("active_pids")

    # reformat in the same way as it happens in the function check_eox()
    items = []
    # value a string as Dict()
    e_api_responses = eval(api_responses)
    for api_response in e_api_responses:
        item = parse_api_response(api_response)

        # append OrderedDict of item to a list of items
        items.append(item)

    # add Active pids to the list "items"
    for pid in active_pids.split(", "):
        item = OrderedDict()
        item["Name"] = pid
        item["Description"] = "Актуально"
        items.append(item)

    # prepare the name of a file
    now = strftime("%Y-%m-%d_%H-%M", localtime())
    filename = f"eox-result_{now}"

    # return as an Excel file
    return make_response_from_records(items, "xls", file_name=filename)


# Result page
@bp_search_cc.route('/search_cc', methods=['GET'])
def _search_cc():
    # collecting passed args and passing them to a form
    args = request.args
    form = PidForm(args)

    # if validation went successfully
    if form.validate():

        # extracting a list of pids
        raw_pids = request.args.get('pids')

        # obtaining configuration to set up a connection to a database
        db = current_app.config['MONGODB_URI']

        # do the job
        version = search_cc_version(db)
        c1, c2, c3, cX, not_found = search_cc_substring(raw_pids, db)

        # prepare the list of not_found
        nf = ", ".join(not_found).strip(", ")

        # return a result
        return render_template(
            'search_cc.html',
            version=version,
            c1=c1,
            c2=c2,
            c3=c3,
            cX=cX,
            nf=nf)

    return render_template("index.html", form=form), 307


# Update db with new xls data
@bp_update_cc.route('/update_cc', methods=['GET', 'POST'])
def _update_cc():
    # entering manually to the page
    if request.method == 'GET':
        # obtaining configuration to set up a connection to a database
        db = current_app.config['MONGODB_URI']
        # grabbing the version
        version = search_cc_version(db)
        # preparing the form
        form = CcFileForm()
        # return just a normal page
        return render_template(
            "update_cc.html", method='get', version=version, form=form)

    # POST method by form action
    elif request.method == 'POST':
        # applying arguments from form to wtform
        form = CcFileForm(request.files)
        # if validation went successfully
        if form.validate():
            file = request.files['ccfile']
            # file = request.files['ccfile'].filename
            name = file.filename
            # making a full path
            full = path.join(".", name)
            filename = secure_filename(full)

            # saving a file locally
            file.save(filename)

            # do the job with the file of this name
            try:
                # obtaining configuration to set up a connection to a database
                db = current_app.config['MONGODB_URI']
                # do the job
                result = update_cc(filename, db)
            except KeyError:
                # if list not found
                return Response("Не найден лист Cisco Product List Russia")
            else:
                # if worked out then show the result
                return render_template(
                    "update_cc.html", method='post', result=result)
            finally:
                # delete the xls file afterall
                remove(filename)

        return render_template("update_cc.html", method='get', form=form), 307


@bp_help.route("/help")
def help():
    return render_template("help.html")

web/eoxer/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Проверка артикула Cisco</title>
    <!-- Bootstrap core CSS -->
    <link href="static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="static/css/mdb.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>

<body>
    <header class="page-header accent-4" style="position: absolute; right: 0; top: 0;">
        <div class="container-fluid">
            <div class="row">
                <a href="mailto:ebelyaev@amt.ru?subject=EOX%20Отзыв&body=Привет.">
                    <button class="btn btn-outline-default waves-effect" type="submit">
                        Отправить отзыв
                    </button>
                </a>
                <a href="{{ url_for('_help.help')}}">
                    <button class="btn btn-outline-default waves-effect" type="submit">
                        Помощь
                    </button>
                </a>
            </div>
        </div>
    </header>
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="static/js/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="static/js/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="static/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="static/js/mdb.min.js"></script>
</body>
</html>

web/eoxer/templates/help.html
{% extends "base.html" %}
{% block content %}
<div class="col">
{% markdown %}

# Страница помощи

## **Зачем это всё надо**

Портал разрабатывался с идеей в первую очередь значительно ускорить выполнение совершенно типовых и рутинных задач проверки актуальности и категории партномеров производителя Cisco Systems.

1. Проверка актуальности через сайт Cisco далека от удобства, а различные поисковые системы могут не показать в выдаче существующий в действительности бюллетень устаревания;
1. Проверка категорий выполняется ручным поиском в файле Excel, что тоже не очень удобно.

Использование удобного вебпортала с поиском сразу по нескольким партномерам и использованием официальных источников данных значительно снижают как время на обработку запросов, так и шанс человеческой ошибки.

## **Функции**

### **Проверка актуальности** (функция EOX)

Функция использует специальный веб-каталог Cisco Systems в публичной сети Интернет.

Функция последовательно выполняет две операции для каждого из представленных партномеров:

* проверка существования партномера;
* проверка актуальности партномера, для существующих партномеров.

Результат не модифицируется порталом никоим образом кроме косметического.
Таким образом, если заведомо известно, что партномер корректный, а результат функции сообщает о его некорректности, значит такого партномера попросту нет в каталоге производителя и функция ничего не может с этим поделать.

### **Проверка крипто- и радиокатегорий** (функция CC)

Функция использует высокоскоростную базу данных, содержащую данные со страницы "Cisco Product List Russia" файла Excel, который сотрудники ТД привыкли использовать для ручного поштучного поиска.
Функция ищет по подстроке, т.е. если искать "2801", результат будет содержать все партномера, которые содержат "2801" в любой части фактического партномера. Это удобно когда надо найти в каких категориях присутствует устройство, в зависимости от разных его партномеров.

**[!]** Обратите внимание, что все категории сворачиваются и разворачиваются кликом мыши по заголовку раздела.

Вверху страницы, свёрнутая по умолчанию, таблица с существующими крипто- и радиокатегориями.

Результат не модифицируется порталом никоим образом кроме косметического.
Таким образом, если заведомо известно, что партномер корректный, а результат функции сообщает, что такой партномер не найден, значит такого партномера попросту не было и в исходном файле Excel и функция ничего не может с этим поделать.

## **Как использовать**

Скопируйте столбец с партномерами прямо в файле Excel и вставьте в поле поиска.
Партномера автоматически разделяются знаком пробел.
Нажмите кнопку проверки, которая вас интересует.
Портал вернёт страницу с результатами проверки.

Помимо самостоятельного ознакомления, вы можете отправить коллеге полный адрес страницы результата, чтобы он мог увидеть его и сам!

Например: [**проверка категории для 2801**](/search_cc?pids=2801)

Удобно, правда?!

## **Известные ограничения**

Текстовое поле для партномеров вмещает до 200 символов.

### Функция EOX

Функция использует веб-каталог производителя, который ограничивает поиск в 5 партномеров в секунду. При поиске большого количестве партномеров, такое ограничение может приводить к продолжительному ожиданию страницы с результатами.

Веб-каталог производителя не содержит сведений по бюджетным коммутаторам производителя (SMB-коммутаторы, серий SG200/300/500).

Если вы найдёте ещё категории отсутствующие в веб-каталоге производителя, пожалуйста, воспользуйтесь кнопкой "Отправить отзыв" в верхнем правом углу, для уведомления администратора.

{% endmarkdown %}
</div>
{% endblock %}

web/eoxer/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="col-lg-12 text-center v-center float-none white mx-auto">
        <h1 class="h1-responsive font-weight-bold text-center my-5">
            <a href="/">Проверка артикула Cisco</a>
        </h1>
        <p class="text-center w-responsive mx-auto mb-7">
            Корректен ли артикул и каков его статус?<br />
            К какой крипто и радиокатегории относится артикул?
        </p>
        <br>
      
        <center>
        <form action="" method="GET" style="width: 50%">

            <div class="md-form form-lg">
                {{ form.pids(class="form-control form-control-lg text-center") }}
                <label for="pids">Укажите артикулы разделяя пробелами</label>
            </div>

            <button class="btn btn-cyan" type="submit" formaction="search_eox">
                    Проверить актуальность
            </button>
            <button class="btn btn-cyan" type="submit" formaction="search_cc">
                    Проверить категорию
            </button>

        </form>
        {% if form.pids.errors %}
            <div class="errors">
                {% for error in form.pids.errors %}
                    <span class="badge badge-warning">
                        {{ error }}
                    </span>
                {% endfor %}
            </div>
        {% endif %}
        </center>

        <br><h3><span class="badge grey">Пример: ISR4451-X/K9 CISCO2801 GE-T=</span></h3>
    </div>
{% endblock %}

web/eoxer/templates/search_cc.html
{% extends "base.html" %}
{% block content %}
    <script language="javascript">
        function toggleDisplay(e){
        element = document.getElementById(e).style;
         if (element.display=='none') {element.display='block';}
         else {element.display='none';}
        }
    </script>

    <a href="/" class="btn btn-blue-grey">Вернуться на главную страницу</a>
    {% if version %}<center><h3><span class="badge pink">Версия таблицы категорий: {{ version }}</span></h3></center>{% endif %}
    <a href="javascript:toggleDisplay('categories')">
        <b><h3><span class="badge blue">Категории</span></h3></b>
    </a>
    <table class="table table-bordered table-striped w-auto" id="categories" style="display:none;">
        <thead class="blue-grey lighten-4">
            <tr>
                <th class="th-sm">Код категории<br></th>
                <th>Описание<br></th>
            </tr>
        </thead>
        <tbody>
            <tr><td><b>С1</b></td><td>продукты, не требующие разрешения на ввоз</td></tr>
            <tr><td><b>С2</b></td><td>продукты, разрешенные ко ввозу без лицензии</td></tr>
            <tr><td><b>С3</b></td><td>продукты, подлежащие импорту с получением лицензии</td></tr>
            <tr><td><b>С4</b></td><td>продукты, не распределенные ни по одной из предыдущих категорий</td></tr>
            <tr><td><b>СL</b></td><td>продукты, относящиеся к локальному производтству</td></tr>
            <tr><td><b>Rn1</b></td><td>устройства, не являющиеся РЭС</td></tr>
            <tr><td><b>Rn2</b></td><td>продукты, относящиеся к локальному производству в РФ </td></tr>
            <tr><td><b>Rn3</b></td><td>РЭС, не требующие получения лицензии на ввоз (при условии декларирования как абонентского оборудования)</td></tr>
            <tr><td><b>Rn4</b></td><td>РЭС, требующие получения лицензии на ввоз. Получена выписка Роскомнадзора из Реестра РЭС/ВЧУ на импортера (для Лицензии МПТ)</td></tr>
            <tr><td><b>Rn5</b></td><td>РЭС, требующие получения лицензии на ввоз и ожидающие прохождения необходимых процедур для включения в Реестр Роскомнадзора РЭС/ВЧУ</td></tr>
            <tr><td><b>Rn6</b></td><td>РЭС, требующие получения лицензии на ввоз в РФ (сопутствующие документы для получения лицензии отсутствуют)</td></tr>
        </tbody>
    </table>
    <hr />


    {% if nf %}
        <b><h3><span class="badge red">Артикулы не найдены:</span></h3></b> {{ nf }}
        <hr />
    {% endif %}

    {% if c1 %}
        <a href="javascript:toggleDisplay('c1')">
            <b><h3><span class="badge green">Криптокатегория С1</span></h3></b>
        </a>
        <table class="table table-bordered table-striped w-auto" id="c1">
            <thead class="blue-grey lighten-4">
                <tr>
                    <th class="th-sm">Артикул<br></th>
                    <th>Криптокатегория<br></th>
                    <th>Радиокатегория<br></th>
                </tr>
            </thead>
            <tbody>
                {% for item in c1 %}
                <tr>
                    <td><b>{{ item['pid'] }}</b></td>
                    <td><b>{{ item['cat_c'] }}</b></td>
                    <td><b>{{ item['cat_r'] }}</b></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <hr />
    {% endif %}

    {% if c2 %}
        <a href="javascript:toggleDisplay('c2')">
            <b><h3><span class="badge green">Криптокатегория С2</span></h3></b>
        </a>
        <table class="table table-bordered table-striped w-auto" id="c2">
            <thead class="blue-grey lighten-4">
                <tr>
                    <th class="th-sm">Артикул<br></th>
                    <th>Криптокатегория<br></th>
                    <th>Радиокатегория<br></th>
                </tr>
            </thead>
            <tbody>
                {% for item in c2 %}
                <tr>
                    <td><b>{{ item['pid'] }}</b></td>
                    <td><b>{{ item['cat_c'] }}</b></td>
                    <td><b>{{ item['cat_r'] }}</b></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <hr />
    {% endif %}

    {% if c3 %}
        <a href="javascript:toggleDisplay('c3')">
            <b><h3><span class="badge red">Криптокатегория С3</span></h3></b>
        </a>
        <table class="table table-bordered table-striped w-auto" id="c3">
            <thead class="blue-grey lighten-4">
                <tr>
                    <th class="th-sm">Артикул<br></th>
                    <th>Криптокатегория<br></th>
                    <th>Радиокатегория<br></th>
                </tr>
            </thead>
            <tbody>
                {% for item in c3 %}
                <tr>
                    <td><b>{{ item['pid'] }}</b></td>
                    <td><b>{{ item['cat_c'] }}</b></td>
                    <td><b>{{ item['cat_r'] }}</b></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <hr />
    {% endif %}

    {% if cX %}
        <a href="javascript:toggleDisplay('cX')">
            <b><h3><span class="badge grey">Криптокатегория С4/CL</span></h3></b>
        </a>
        <table class="table table-bordered table-striped w-auto" id="cX">
            <thead class="blue-grey lighten-4">
                <tr>
                    <th class="th-sm">Артикул<br></th>
                    <th>Криптокатегория<br></th>
                    <th>Радиокатегория<br></th>
                </tr>
            </thead>
            <tbody>
                {% for item in cX %}
                <tr>
                    <td><b>{{ item['pid'] }}</b></td>
                    <td><b>{{ item['cat_c'] }}</b></td>
                    <td><b>{{ item['cat_r'] }}</b></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <hr />
    {% endif %}  
{% endblock %}

web/eoxer/templates/search_eox.html
{% extends "base.html" %}
{% block content %}
    <a href="/" class="btn btn-blue-grey">Вернуться на главную страницу</a>
    <form action="export_eox" method="post">
        <input type="hidden" name="api_responses" value="{{ api_responses }}" />
        {% if active_pids %}
        <input type="hidden" name="active_pids" value="{{ active_pids }}" />
        {% endif %}
        <input type="submit" name="submit" value="Экспортировать в Excel" class="btn btn-blue">
     </form>
     {{ full_api_response }}
    {% if obsolete_pids %}
        <b><h3><span class="badge red">Артикулы устаревшие (дата EoL достигнута):</span></h3></b>
        <table class="table table-bordered table-striped">
            <thead class="blue-grey lighten-4">
                <tr>
                    <th class="th-sm">Наименование<br></th>
                    <th>Описание<br></th>
                    <th>Дата EoSale</th>
                    <th>Бюллетень<br></th>
                    <th>Дата анонса</th>
                    <th>Дата EoSupport</th>
                    <th>Дата EoSvcRenew<br></th>
                    <th>Замена</th>
                    <th>Описание замены</th>
                    <th>Информация о замене<br></th>
                </tr>
            </thead>
            <tbody>
                {% for item in obsolete_pids %}
                <tr>
                    <td><b>{{ item['Name'] }}</b></td>
                    <td>{{ item["Description"] }}</td>
                    <td>{{ item["EoSale"] }}</td>
                    <td>
                    {% if item["BulletinURL"] != " " %}
                        <a href="{{ item["BulletinURL"] }}"
                        class="btn btn-primary btn-rounded btn-sm my-0"
                        target="external">
                            Ссылка
                        </a>
                    {% else %}
                        Нет
                    {% endif %}
                    </td>
                    <td>{{ item["BulletinDate"] }} </tdh>
                    <td>{{ item["EoSupport"] }}</tdh>
                    <td>{{ item["EoSvcRenew"] }}</td>
                    <td>{{ item["ReplacementPID"] }}</td>
                    <td>{{ item["PIDDescription"] }}</td>
                    <td>
                    {% if item["PIDInfoURL"] != " " %}
                        <a href="{{ item["PIDInfoURL"] }}"
                        class="btn btn-primary btn-rounded btn-sm my-0"
                        target="external">
                            Ссылка
                        </a>
                    {% else %}
                        Нет
                    {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    <hr />
    {% endif %}

    {% if eox_pids %}
        <b><h3><span class="badge orange">Артикулы устаревающие (дата EoL не достигнута):</span></h3></b>
        <table class="table table-bordered table-striped">
            <thead class="blue-grey lighten-4">
                <tr>
                    <th class="th-sm">Наименование<br></th>
                    <th>Описание<br></th>
                    <th>Дата EoSale</th>
                    <th>Бюллетень<br></th>
                    <th>Дата анонса</th>
                    <th>Дата EoSupport</th>
                    <th>Дата EoSvcRenew<br></th>
                    <th>Замена</th>
                    <th>Описание замены</th>
                    <th>Информация о замене<br></th>
                </tr>
            </thead>
            <tbody>
                {% for item in eox_pids %}
                <tr>
                    <td><b>{{ item['Name'] }}</b></td>
                    <td>{{ item["Description"] }}</td>
                    <td>{{ item["EoSale"] }}</td>
                    <td>
                    {% if item["BulletinURL"] != " " %}
                        <a href="{{ item["BulletinURL"] }}"
                        class="btn btn-primary btn-rounded btn-sm my-0"
                        target="external">
                            Ссылка
                        </a>
                    {% else %}
                        Нет
                    {% endif %}
                    </td>
                    <td>{{ item["BulletinDate"] }} </tdh>
                    <td>{{ item["EoSupport"] }}</tdh>
                    <td>{{ item["EoSvcRenew"] }}</td>
                    <td>{{ item["ReplacementPID"] }}</td>
                    <td>{{ item["PIDDescription"] }}</td>
                    <td>
                    {% if item["PIDInfoURL"] != " " %}
                        <a href="{{ item["PIDInfoURL"] }}"
                        class="btn btn-primary btn-rounded btn-sm my-0"
                        target="external">
                            Ссылка
                        </a>
                    {% else %}
                        Нет
                    {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    <hr />
    {% endif %}
        
    {% if active_pids %}
        <b><h3><span class="badge green">Артикулы актуальные:</span></h3></b> {{ active_pids }}
        <hr />
    {% endif %}
    
    {% if wrong_pids %}
        <b><h3><span class="badge grey">Артикулы не найдены в базе Cisco:</span></h3></b> {{ wrong_pids }}
        <hr />
    {% endif %}

{% endblock %}

web/eoxer/templates/update_cc.html
{% extends "base.html" %}
{% block content %}
    <a href="/" class="btn btn-blue-grey">Вернуться на главную страницу</a><br><br>
    <div class="col-lg-12 text-center v-center float-none white mx-auto">
        <h1 class="h1-responsive font-weight-bold text-center my-5">
            <a href="{{ url_for('_update_cc._update_cc') }}">Обновить версию таблицы</a>
        </h1>
        <br>
      
        <center>
        {% if method == 'get' %}
        <form action="{{ url_for('_update_cc._update_cc') }}" method="POST" style="width: 50%" enctype="multipart/form-data">

            <div class="md-form form-lg" >
                {{ form.ccfile(class="form-control form-control-lg text-center") }}
            </div>
            
            {% if form.ccfile.errors %}
            <div class="errors">
                {% for error in form.ccfile.errors %}
                    <span class="badge badge-warning">
                        {{ error }}
                    </span>
                {% endfor %}
            </div>
            {% endif %}

            <button class="btn btn-cyan" type="submit">
                    Обновить
            </button>
            {% if version %}
                <br /><b><h4><span class="badge green">Версия таблицы: {{ version }}</span></h4></b>
            {% endif %}

        </form>
        {% endif %}
        {% if method == 'post' %}
            {% if version %}
            {% endif %}
            {% if result %}
                <br /><b><h4><span class="badge green">Добавлено записей: {{ result['count'] }}</span></h4></b>
                <br /><b><h4><span class="badge green">Обновлено с {{ result['old_version'] }} до {{ result['new_version'] }}</span></h4></b>
            {% else %}
                <br /><b><h4><span class="badge warning">Что-то пошло не так</span></h4></b>
            {% endif %}
        {% endif %}
        </center>
    </div>
{% endblock %}